envVarGroups:
  - name: spree-envs
    envVars:
      - key: DB_POOL
        value: 10

databases:
  - name: spree-db
    databaseName: spree_production
    user: spree
    plan: free

services:
  - type: web
    name: spree-web
    env: ruby
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: RAILS_MASTER_KEY
        sync: false
      - key: SECRET_KEY_BASE
        value: 754749b0727d806e70dc958611a503322f28882f2256568fd9c31ce67c696cc4e18fc6a9bb017f228ccd72b89e65a5291dde3a06e37b8c81ab212d3afdcea6b3
      - key: DATABASE_URL
        fromDatabase:
          name: spree-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          name: spree-redis
          type: redis
          property: connectionString
      - key: RAILS_ENV
        value: production
      - key: RAILS_SERVE_STATIC_FILES
        value: true

  - type: worker
    name: spree-worker
    runtime: ruby
    plan: hobby
    buildCommand: bin/render-build.sh
    startCommand: bundle exec sidekiq
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: spree-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: keyvalue
          name: keyvalue
          property: connectionString
      - key: SECRET_KEY_BASE
        sync: false
      - key: REDIS_CACHE_URL
        fromService:
          type: keyvalue
          name: keyvalue-cache
          property: connectionString
      - fromGroup: spree-envs
  
  - type: keyvalue
    name: keyvalue
    ipAllowList: []
    plan: hobby
    maxmemoryPolicy: noeviction

  - type: keyvalue
    name: keyvalue-cache
    ipAllowList: []
    plan: hobby
    maxmemoryPolicy: allkeys-lru

redis:
  - name: spree-redis
    plan: free